// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeTLink.Data;

#nullable disable

namespace VeTLink.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217161957_Error500Db")]
    partial class Error500Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SucursalVeterinario", b =>
                {
                    b.Property<int>("SucursalesAsignadasId")
                        .HasColumnType("int");

                    b.Property<Guid>("VeterinariosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SucursalesAsignadasId", "VeterinariosId");

                    b.HasIndex("VeterinariosId");

                    b.ToTable("SucursalVeterinario");
                });

            modelBuilder.Entity("VeTLink.Models.Alergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("HistorialMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sustancia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistorialMedicoId");

                    b.ToTable("Alergias");
                });

            modelBuilder.Entity("VeTLink.Models.Bano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarnetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximoBano")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarnetId");

                    b.ToTable("Banos");
                });

            modelBuilder.Entity("VeTLink.Models.CarnetPreventivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carnet");
                });

            modelBuilder.Entity("VeTLink.Models.Cirugia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistorialMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HistorialMedicoId");

                    b.HasIndex("TipoId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Cirugias");
                });

            modelBuilder.Entity("VeTLink.Models.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreClinica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuscripcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("VeTLink.Models.Comportamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comportamientos");
                });

            modelBuilder.Entity("VeTLink.Models.ComportamientoSocializacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompProblematico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistorialMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NivelActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReaccionAnimalId")
                        .HasColumnType("int");

                    b.Property<int>("ReaccionPersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistorialMedicoId");

                    b.HasIndex("NivelActividadId");

                    b.HasIndex("ReaccionAnimalId");

                    b.HasIndex("ReaccionPersonaId");

                    b.ToTable("ComportamientosSocializacion");
                });

            modelBuilder.Entity("VeTLink.Models.CondicionCorporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CondicionesCorporal");
                });

            modelBuilder.Entity("VeTLink.Models.ConsultaMedica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DiagnosticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExploracionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InicioSintomas")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MascotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("int");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("ExploracionId");

                    b.HasIndex("MascotaId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("TipoServicioId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("VeTLink.Models.Desparasitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarnetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreMedicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximaAplicacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarnetId");

                    b.ToTable("Desparasitaciones");
                });

            modelBuilder.Entity("VeTLink.Models.Diagnostico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiagnosticoDefinitivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoPresuntivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("VeTLink.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoInt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("VeTLink.Models.Dueno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Duenos");
                });

            modelBuilder.Entity("VeTLink.Models.Enfermedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enfermedades");
                });

            modelBuilder.Entity("VeTLink.Models.Error", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeDeError")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Errores");
                });

            modelBuilder.Entity("VeTLink.Models.EstadoGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosGeneral");
                });

            modelBuilder.Entity("VeTLink.Models.EstadoSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSuscripcion");
                });

            modelBuilder.Entity("VeTLink.Models.EventoCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MascotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("bit");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("VeTLink.Models.EvidenciaEvolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EvolucionClinicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URLArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvolucionClinicaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("EvidenciasEvolucion");
                });

            modelBuilder.Entity("VeTLink.Models.EvolucionClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultaMedicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasMedico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaMedicaId");

                    b.ToTable("EvolucionesClinicas");
                });

            modelBuilder.Entity("VeTLink.Models.ExploracionFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CondicionCorporalId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoGeneralId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int?>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<int?>("HidratacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("LlenadoCapilar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("MucosasId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TemperaturaCorporal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TemperaturaRectal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CondicionCorporalId");

                    b.HasIndex("EstadoGeneralId");

                    b.HasIndex("HidratacionId");

                    b.HasIndex("MucosasId");

                    b.ToTable("ExploracionesFisicas");
                });

            modelBuilder.Entity("VeTLink.Models.Hidratacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hidrataciones");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialEnfermedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnfermedadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistorialMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnfermedadId");

                    b.HasIndex("HistorialMedicoId");

                    b.ToTable("HistorialEnfermedades");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistorialReproductivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistorialReproductivoId");

                    b.ToTable("HistorialesMedicos");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialReproductivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Esterilizado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEsterilizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Montas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrimeraGesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaGesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoCelo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HistorialesReproductivos");
                });

            modelBuilder.Entity("VeTLink.Models.Mascota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CarnetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DuenoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistorialMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarnetId");

                    b.HasIndex("DuenoId");

                    b.HasIndex("HistorialMedicoId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("VeTLink.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.Property<int>("ViaAdministracionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.HasIndex("ViaAdministracionId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("VeTLink.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreModulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("VeTLink.Models.Mucosa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mucosas");
                });

            modelBuilder.Entity("VeTLink.Models.NivelActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelActividades");
                });

            modelBuilder.Entity("VeTLink.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("TipoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("VeTLink.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("VeTLink.Models.Profilaxis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarnetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximaAplicacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarnetId");

                    b.ToTable("LimpiezaProfilaxis");
                });

            modelBuilder.Entity("VeTLink.Models.PruebaLaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchivoResultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DiagnosticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoPruebaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("TipoPruebaId");

                    b.ToTable("PruebasLaboratorios");
                });

            modelBuilder.Entity("VeTLink.Models.ReaccionSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReaccionesSociales");
                });

            modelBuilder.Entity("VeTLink.Models.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.Property<string>("URLArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("VeTLink.Models.SintomaActual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ComportamientoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ConsultaMedicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionSintomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionCantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadTiempoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComportamientoId");

                    b.HasIndex("ConsultaMedicaId");

                    b.HasIndex("UnidadTiempoId");

                    b.ToTable("SintomasActuales");
                });

            modelBuilder.Entity("VeTLink.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("DireccionId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("VeTLink.Models.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoSuscripcionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<bool>("Renovacion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId")
                        .IsUnique()
                        .HasFilter("[ClinicaId] IS NOT NULL");

                    b.HasIndex("EstadoSuscripcionId");

                    b.HasIndex("PlanId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("VeTLink.Models.TipoCirugia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposCirugias");
                });

            modelBuilder.Entity("VeTLink.Models.TipoPrueba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Prueba")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposPruebas");
                });

            modelBuilder.Entity("VeTLink.Models.TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposServicios");
                });

            modelBuilder.Entity("VeTLink.Models.TipoTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposTratamientos");
                });

            modelBuilder.Entity("VeTLink.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuarios");
                });

            modelBuilder.Entity("VeTLink.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoTratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoTratamientoId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("VeTLink.Models.UnidadTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesTiempo");
                });

            modelBuilder.Entity("VeTLink.Models.Vacuna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarnetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreVacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProximaAplicacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarnetId");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("VeTLink.Models.Veterinario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CedulaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("VeTLink.Models.ViaAdministracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Via")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViasAdministracion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SucursalVeterinario", b =>
                {
                    b.HasOne("VeTLink.Models.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("SucursalesAsignadasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Veterinario", null)
                        .WithMany()
                        .HasForeignKey("VeterinariosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VeTLink.Models.Alergia", b =>
                {
                    b.HasOne("VeTLink.Models.HistorialMedico", null)
                        .WithMany("Alergias")
                        .HasForeignKey("HistorialMedicoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VeTLink.Models.Bano", b =>
                {
                    b.HasOne("VeTLink.Models.CarnetPreventivo", "Carnet")
                        .WithMany("RegistroBanos")
                        .HasForeignKey("CarnetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carnet");
                });

            modelBuilder.Entity("VeTLink.Models.Cirugia", b =>
                {
                    b.HasOne("VeTLink.Models.HistorialMedico", "HistorialMedico")
                        .WithMany()
                        .HasForeignKey("HistorialMedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.TipoCirugia", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistorialMedico");

                    b.Navigation("Tipo");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeTLink.Models.ComportamientoSocializacion", b =>
                {
                    b.HasOne("VeTLink.Models.HistorialMedico", "HistorialMedico")
                        .WithMany()
                        .HasForeignKey("HistorialMedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.NivelActividad", "NivelActividad")
                        .WithMany()
                        .HasForeignKey("NivelActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.ReaccionSocial", "ReaccionAnimal")
                        .WithMany()
                        .HasForeignKey("ReaccionAnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.ReaccionSocial", "ReaccionPersona")
                        .WithMany()
                        .HasForeignKey("ReaccionPersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistorialMedico");

                    b.Navigation("NivelActividad");

                    b.Navigation("ReaccionAnimal");

                    b.Navigation("ReaccionPersona");
                });

            modelBuilder.Entity("VeTLink.Models.ConsultaMedica", b =>
                {
                    b.HasOne("VeTLink.Models.Diagnostico", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.ExploracionFisica", "Exploracion")
                        .WithMany()
                        .HasForeignKey("ExploracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Mascota", "Mascota")
                        .WithMany("Consultas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Exploracion");

                    b.Navigation("Mascota");

                    b.Navigation("Receta");

                    b.Navigation("TipoServicio");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeTLink.Models.Desparasitacion", b =>
                {
                    b.HasOne("VeTLink.Models.CarnetPreventivo", "Carnet")
                        .WithMany("RegistroDesparasitaciones")
                        .HasForeignKey("CarnetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carnet");
                });

            modelBuilder.Entity("VeTLink.Models.Dueno", b =>
                {
                    b.HasOne("VeTLink.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VeTLink.Models.EventoCalendario", b =>
                {
                    b.HasOne("VeTLink.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("VeTLink.Models.EvidenciaEvolucion", b =>
                {
                    b.HasOne("VeTLink.Models.EvolucionClinica", null)
                        .WithMany("Evidencias")
                        .HasForeignKey("EvolucionClinicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VeTLink.Models.EvolucionClinica", b =>
                {
                    b.HasOne("VeTLink.Models.ConsultaMedica", null)
                        .WithMany("Evoluciones")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VeTLink.Models.ExploracionFisica", b =>
                {
                    b.HasOne("VeTLink.Models.CondicionCorporal", "CondicionCorporal")
                        .WithMany()
                        .HasForeignKey("CondicionCorporalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.EstadoGeneral", "EstadoGeneral")
                        .WithMany()
                        .HasForeignKey("EstadoGeneralId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Hidratacion", "Hidratacion")
                        .WithMany()
                        .HasForeignKey("HidratacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Mucosa", "Mucosas")
                        .WithMany()
                        .HasForeignKey("MucosasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CondicionCorporal");

                    b.Navigation("EstadoGeneral");

                    b.Navigation("Hidratacion");

                    b.Navigation("Mucosas");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialEnfermedad", b =>
                {
                    b.HasOne("VeTLink.Models.Enfermedad", "Enfermedad")
                        .WithMany()
                        .HasForeignKey("EnfermedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.HistorialMedico", "HistorialMedico")
                        .WithMany("Enfermedades")
                        .HasForeignKey("HistorialMedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enfermedad");

                    b.Navigation("HistorialMedico");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialMedico", b =>
                {
                    b.HasOne("VeTLink.Models.HistorialReproductivo", "HistorialReproductivo")
                        .WithMany()
                        .HasForeignKey("HistorialReproductivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistorialReproductivo");
                });

            modelBuilder.Entity("VeTLink.Models.Mascota", b =>
                {
                    b.HasOne("VeTLink.Models.CarnetPreventivo", "Carnet")
                        .WithMany()
                        .HasForeignKey("CarnetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeTLink.Models.Dueno", "Dueno")
                        .WithMany("Mascotas")
                        .HasForeignKey("DuenoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.HistorialMedico", "HistorialMedico")
                        .WithMany()
                        .HasForeignKey("HistorialMedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carnet");

                    b.Navigation("Dueno");

                    b.Navigation("HistorialMedico");
                });

            modelBuilder.Entity("VeTLink.Models.Medicamento", b =>
                {
                    b.HasOne("VeTLink.Models.Tratamiento", null)
                        .WithMany("Medicamentos")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.ViaAdministracion", "ViaAdministracion")
                        .WithMany()
                        .HasForeignKey("ViaAdministracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ViaAdministracion");
                });

            modelBuilder.Entity("VeTLink.Models.Modulo", b =>
                {
                    b.HasOne("VeTLink.Models.Plan", null)
                        .WithMany("Modulos")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VeTLink.Models.Persona", b =>
                {
                    b.HasOne("VeTLink.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Direccion");

                    b.Navigation("TipoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VeTLink.Models.Profilaxis", b =>
                {
                    b.HasOne("VeTLink.Models.CarnetPreventivo", "Carnet")
                        .WithMany("RegistroProfilaxis")
                        .HasForeignKey("CarnetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carnet");
                });

            modelBuilder.Entity("VeTLink.Models.PruebaLaboratorio", b =>
                {
                    b.HasOne("VeTLink.Models.Diagnostico", null)
                        .WithMany("Pruebas")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.TipoPrueba", "TipoPrueba")
                        .WithMany()
                        .HasForeignKey("TipoPruebaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoPrueba");
                });

            modelBuilder.Entity("VeTLink.Models.Receta", b =>
                {
                    b.HasOne("VeTLink.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("VeTLink.Models.SintomaActual", b =>
                {
                    b.HasOne("VeTLink.Models.Comportamiento", "Comportamiento")
                        .WithMany()
                        .HasForeignKey("ComportamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.ConsultaMedica", null)
                        .WithMany("Sintomas")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.UnidadTiempo", "UnidadTiempo")
                        .WithMany()
                        .HasForeignKey("UnidadTiempoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Comportamiento");

                    b.Navigation("UnidadTiempo");
                });

            modelBuilder.Entity("VeTLink.Models.Sucursal", b =>
                {
                    b.HasOne("VeTLink.Models.Clinica", "Clinica")
                        .WithMany("Sucursales")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinica");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("VeTLink.Models.Suscripcion", b =>
                {
                    b.HasOne("VeTLink.Models.Clinica", "Clinica")
                        .WithOne("Suscripcion")
                        .HasForeignKey("VeTLink.Models.Suscripcion", "ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.EstadoSuscripcion", "EstadoSuscripcion")
                        .WithMany()
                        .HasForeignKey("EstadoSuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeTLink.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinica");

                    b.Navigation("EstadoSuscripcion");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("VeTLink.Models.Tratamiento", b =>
                {
                    b.HasOne("VeTLink.Models.TipoTratamiento", "TipoTratamiento")
                        .WithMany()
                        .HasForeignKey("TipoTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoTratamiento");
                });

            modelBuilder.Entity("VeTLink.Models.Vacuna", b =>
                {
                    b.HasOne("VeTLink.Models.CarnetPreventivo", "Carnet")
                        .WithMany("RegistroVacunas")
                        .HasForeignKey("CarnetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carnet");
                });

            modelBuilder.Entity("VeTLink.Models.Veterinario", b =>
                {
                    b.HasOne("VeTLink.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VeTLink.Models.CarnetPreventivo", b =>
                {
                    b.Navigation("RegistroBanos");

                    b.Navigation("RegistroDesparasitaciones");

                    b.Navigation("RegistroProfilaxis");

                    b.Navigation("RegistroVacunas");
                });

            modelBuilder.Entity("VeTLink.Models.Clinica", b =>
                {
                    b.Navigation("Sucursales");

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("VeTLink.Models.ConsultaMedica", b =>
                {
                    b.Navigation("Evoluciones");

                    b.Navigation("Sintomas");
                });

            modelBuilder.Entity("VeTLink.Models.Diagnostico", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("VeTLink.Models.Dueno", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeTLink.Models.EvolucionClinica", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("VeTLink.Models.HistorialMedico", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Enfermedades");
                });

            modelBuilder.Entity("VeTLink.Models.Mascota", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("VeTLink.Models.Plan", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("VeTLink.Models.Tratamiento", b =>
                {
                    b.Navigation("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
